### ISSUE TITLE
版本更新后如何获取 byte[] videoframe

### ISSUE THREAD

**Issue by yuanjunli** [aiyaapp/AiyaEffectsAndroid#54]
在 4.0版本中有没有接口设置回调获取到每一帧的数据。在3.3版本中CamerView 有提供一个setFrameCallback（）的接口

**Comment by ruanrongding** [comment]
有的，现在下班明天弄吧laughing-------- 原始邮件 --------主题：[aiyaapp/AiyaEffectsAndroid] 版本更新后如何获取 byte[] videoframe (#54)发件人：NEXTB 收件人：aiyaapp/AiyaEffectsAndroid 抄送：Subscribed 在 4.0版本中有没有接口设置回调获取到每一帧的数据。在3.3版本中CamerView 有提供一个setFrameCallback（）的接口

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aiyaapp/AiyaEffectsAndroid","title":"aiyaapp/AiyaEffectsAndroid","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aiyaapp/AiyaEffectsAndroid"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"版本更新后如何获取 byte[] videoframe (#54)"}],"action":{"name":"View Issue","url":"https://github.com/aiyaapp/AiyaEffectsAndroid/issues/54"}}}

**Comment by yuanjunli** [comment]
提供一下获取的方法

**Comment by yuanjunli** [comment]
@ruanrongding 在线等获取videoframe的方法

**Comment by ruanrongding** [comment]
CameraRecorder2类中可以通过设置takePictureListener来获取每一帧的数据

**Comment by aiyaapp** [comment]
no more questions, close the issue.
